### ISSUE TITLE
Fix the bug with the generation expression

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/white-generator#28]
```
Traceback (most recent call last):
  File "/home/thewizardplusplus/.local/bin/white-generator", line 5, in <module>
    from white_generator import main
  File "/home/thewizardplusplus/.local/lib/python3.10/site-packages/white_generator/__init__.py", line 2, in <module>
    from .main import main
  File "/home/thewizardplusplus/.local/lib/python3.10/site-packages/white_generator/main.py", line 11, in <module>
    from . import generation
  File "/home/thewizardplusplus/.local/lib/python3.10/site-packages/white_generator/generation.py", line 5, in <module>
    from . import text
  File "/home/thewizardplusplus/.local/lib/python3.10/site-packages/white_generator/text.py", line 36
    fit_text(draw, line, text_parameters, font)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Generator expression must be parenthesized
```

**Comment by thewizardplusplus** [comment]
See https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior, point number 4.
